#!/usr/bin/python3
#need this for a workaround.
import subprocess
print("run with elevated permissions!")

gpu = input("What gpu do you have?the supported ones are amd gpus intel igpus:")

if gpu == "amd":
  subprocess.run(["mkdir", "/etc/X11/xorg.conf.d"])
  file = open("/etc/X11/xorg.conf.d/20-amdgpu.conf", "w")
  file.write("""
Section "Device"
    Identifier  "AMD Graphics"
    Driver      "amdgpu"
    Option      "TearFree"  "true"
EndSection""""")
  file.close()
  
elif gpu == "intel":
  subprocess.run(["mkdir", "/etc/X11/xorg.conf.d"])
  file = open("/etc/X11/xorg.conf.d/20-intel-gpu.conf", "w")
  file.write("""
Section "Device"
    Identifier  "Intel Graphics"
    Driver      "intel"
    Option      "TearFree"  "true"
EndSection""""")
  file.close()
#ofcourse nvidia being weird and not using xorg.conf.d
elif gpu == "nvidia":
  print("hacky fix, stops working after reboot, go into nvidia-settings and change it yourself")
  subprocess.run(["nvidia-settings", """--assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"""""])
